### ISSUE TITLE
Enabling object cache breaks wp-admin

### ISSUE THREAD

**Issue by MozMorris** [tillkruss/Redis-Object-Cache#1]
Thanks for your work on this. I've had it working but when I recently disabled & re-enabled the cache, I'm left with the following:

![screen shot 2015-05-01 at 09 27 36](https://cloud.githubusercontent.com/assets/156303/7428220/5cc4a52e-efe4-11e4-93a6-0fb8fdb67aa2.png)

URI: `/wp-admin/upgrade.php?_wp_http_referer=%2Fwp%2Fwp-admin%2Ftools.php%3Fpage%3Dredis-cache%26message%3Dcache-enabled`

Wherever I navigate in the admin, I'm redirected to the above. This doesn't affect the front-end of the site which continues to work as normal.

WordPress: 4.2.1
Redis Object Cache: 1.1.1

The cause could be another plugin but it's worth opening an issue here because this might be a common problem.

**Comment by tillkruss** [comment]
What happens if you request `/wp-admin/` without any referrer?

**Comment by MozMorris** [comment]
Same thing.

**Comment by tillkruss** [comment]
What URL are you redirect to?

**Comment by MozMorris** [comment]
/wp-admin/upgrade.php?_wp_http_referer=%2Fwp%2Fwp-admin%2F

**Comment by tillkruss** [comment]
Mhh, try deleting `/wp-content/object-cache.php`.

**Comment by MozMorris** [comment]
Which fixes the upgrade/redirect but then obviously the cache is not enabled.

**Comment by tillkruss** [comment]
Okay, try to flush the entire Redis database.

**Comment by MozMorris** [comment]
That fixed it.

**Comment by MozMorris** [comment]
@tillkruss thanks for your help with this. I'll leave it to you to close or keep open this issue. 👍

**Comment by tillkruss** [comment]
Great. I'll look closer into this if more people experience this issue, might have been some weird corner case.

**Comment by jamiehannaford** [comment]
@tillkruss I'm also running into this problem. Flushing the Redis cache doesn't fix; the only thing that works is renaming `object-cache.php` to something else.

**Comment by jamiehannaford** [comment]
@tillkruss If I delete the DB and reinstall, I'm no longer seeing the upgrade DB screen. Instead I'm getting a redirect loop on the admin login:

> wp-login.php?redirect_to=http%3A%2F%2F{IP_ADDRESS}%2Fwp-admin%2Fprofile.php&reauth=1

Is it a problem with Redis retaining and retrieving the admin session?

**Comment by MozMorris** [comment]
@jamiehannaford as a workaround, I always disable the cache before I do anything code/db/admin related.

I'm hosting on a ephemeral filesystem so I have to do this on every deploy, otherwise I get the redirect.

**Comment by MozMorris** [comment]
I'm not certain but perhaps flushing the cache when activating the plugin might help?

https://github.com/tillkruss/Redis-Object-Cache/blob/master/redis-cache.php#L279

**Comment by tillkruss** [comment]
@jamiehannaford: Can you tell me exactly what happened and what the exact issue was? Maybe you flushed the Redis database too soon or late, because the has to work. Unless it's caching issue from another plugin.

@MozMorris: Yeah, I usually just flush the Redis database when I get weird loops like that. I'm eager to find a fix for this, tho.

**Comment by jamiehannaford** [comment]
@tillkruss I switched from [Predis](https://github.com/nrk/predis) to the [Redis](https://github.com/phpredis/phpredis) ext and it seems to have fixed the issue :+1:

**Comment by tillkruss** [comment]
@jamiehannaford: Great!

**Comment by firmanherdiansyah** [comment]
You all save my life . thanks for solving this issue

**Comment by shafeeqts** [comment]
i got this issue 1st time when update to 4.7

bro @tillkruss can you explain about to do this --> "Try to flush the entire Redis database."

note: am not advanced user and simple user.

thanks advance :)

**Comment by tillkruss** [comment]
@shafeeqts: It depends on your setup, the easiest way is to use `redis-cli` to connect to your Redis server and then execute `FLUSHDB`. Alternatively you can use WP-CLI on your server and execute `wp cache flush`.

**Comment by shafeeqts** [comment]
don't know about redis server, execute flushdb, etc

that's good if give step by step guide.

**Comment by tillkruss** [comment]
Sorry, caching is not for beginners. Please Google it or ask your hosting provider for help.

**Comment by shafeeqts** [comment]
ok  thanks  :)

**Comment by rjsears** [comment]
Just to jump in here, was having the same issue using Redis 4.1.1 and flushing the cache did the trick for me as well.

**Comment by floatbeta** [comment]
I have been having an issue where wp-admin is being cached.

**Comment by floatbeta** [comment]
> I have been having an issue where wp-admin is being cached.

I fixed it. 

#1. I am using Cloudflare so a page rule to bypass the cache.
#2. Redis Object Cache
#3. Nginx Cache
#4. Cloudflare page cache

**Comment by VGzsysadm** [comment]
> 
> 
> > I have been having an issue where wp-admin is being cached.
> 
> I fixed it.
> 
> #1. I am using Cloudflare so a page rule to bypass the cache.
> #2. Redis Object Cache
> #3. Nginx Cache
> #4. Cloudflare page cache

Could you explain your scenario?.

I have exactly the same issue, i have a bypass for wp-admin in cloudflare

This is my config in wp-config:

//** Redis Config. */
define('WP_CACHE', true);
define('WP_REDIS_SCHEME', 'unix');
define('WP_REDIS_PATH', '/var/run/redis/redis.sock');
define('WP_REDIS_IGNORED_GROUPS', 'user_meta');

If i flush the cache the first logon works, the next one no.
