### ISSUE TITLE
Question: Wordpress Object Cache and Page Cache 

### ISSUE THREAD

**Issue by rmalenko** [tillkruss/Redis-Object-Cache#14]
Hi!
Could you tell me, please, will Object Cache (Redis) и Page Cache (Nginx) complement each other or will conflict cached version?

Regards,
Rostyslav

**Comment by tillkruss** [comment]
They work perfectly together. One is a Object Cache for WordPress, the other one is just for clearing the Nginx cache.

**Comment by rmalenko** [comment]
Thank you!
In this case a will use Nginx microcache together with Redis-server.
