### ISSUE TITLE
wp_cache_flush clears entire Redis and not just current site?

### ISSUE THREAD

**Issue by jeremyclarke** [tillkruss/Redis-Object-Cache#16]
Hi there, thanks so much for this plugin! It's got all the features we need so really appreciated. 

Looking at $wp_object_cache->flush it seems like any time wp_cache_flush() is called, the entire Redis library gets cleared. Is that right, or is it only keys related to the current site that would get flushed?

We're running Redis and your plugin on a huge server with dozens of sites, each identified by the WP_CACHE_KEY_SALT constant (using their db names). It seems to me that if wp_cache_flush() is run on one of those sites it should only clear the keys for that site. 

Thanks for any clarification! We're trying to make sure it's working properly and seeing a regular emptying of Redis so I want to discount this fear as a possibility.

**Comment by tillkruss** [comment]
`wp_cache_flush()` triggers Redis' [FLUSHDB](http://redis.io/commands/FLUSHDB) command, so yes the entire database will be flushed if it's shared with other installations.

I'd recommend to use a separate Redis database for each separate installation.

If you like to you can submit a PR that alters the `flush()` method that lists all [KEYS](http://redis.io/commands/KEYS) if the `WP_CACHE_KEY_SALT` is present and deletes them. That might take much longer than `FLUSHDB`, tho.

**Comment by jeremyclarke** [comment]
Thanks for the confirmation! Very helpful. We'll take a look at sending you that PR. For us a slightly less performant flush probably wouldn't be a big problem compared to the whole db getting reset. 

I'll also do a review of our plugins that might be triggering a full flush. I bet one of them is just being stupid and flushing the whole DB when they should be flushing a single group or something.

**Comment by jeremyclarke** [comment]
We're still planning to work out a fix for this.

**Comment by carlalexander** [comment]
Just going to follow up on this. Redis doesn't support pattern match with the `DEL` command. Flushing the cache that way would require that you fetch all the keys and delete them one at a time.
