### ISSUE TITLE
Please add filters/actions to get/set/delete calls so we can set up logging/fix bugs in core

### ISSUE THREAD

**Issue by jeremyclarke** [tillkruss/Redis-Object-Cache#18]
Hi and thanks for the plugin!

**Context**
After having redis-object-cache on for a few weeks we got a steady stream of instances where sites would white-screen-of-death on both the theme and admin. The only thing that fixed it was flushing the object cache, and I tracked it down to a bug in core WP related to how it stores and updates `alloptions`. There is a race condition where two processes updating an autoloaded option step on each other's edits because they don't refresh their internal copy of `alloptions` before inserting the single value they needed to change. 
https://core.trac.wordpress.org/ticket/31245

In our case these collisions caused the WSOD, but to figure that out we had to add logging of SET/DELETE commands to track when/how the problem was triggered. To solve the problem we had to look through the logs and find the code that was re-saving options too often, as well as adding a hack that resets `alloptions` whenever it's saved (i'll make another ticket about that). 

Either way we had to change our copy of `object-cache.php` to get it done, and we're hoping you can incorporate some similar changes into the official version since they are harmless and simple. 

**What we need**

The essence of what we want is just an action and a filter in each of the main Redis command methods (GET, SET, DELETE and any others you consider appropriate, those where the ones we needed). 

Action example: At the end of `WP_Object_Cache->set()`

```php
	do_action('redis_object_cache_set', $key, $value, $group, $expiration);
```

Filter+action example: At the end of `WP_Object_Cache->get()`

```php
	$value = is_object( $value ) ? clone $value : $value;
	do_action('redis_object_cache_set', $key, $value, $group);
	return apply_filters('redis_object_cache_get', $value, $key, $group);
```

IMHO it's worth adding both a filter and action to GET and SET though in our case we only really need the filter on GET, so if you want to limit the number of filters for some reason then we'd be satisfied if the other methods only got actions. 

There's no real penalty to having filters/actions until they are used, so adding these shouldn't affect the performance of anyone unless they start writing code to interact with them. To me this kind of action/filter usage is a best-practice and great future-proofing. They will let us fix our own problems easily and give you time to integrate fixes when convenient without us having to constantly fork the `object-cache.php` file. 

Thanks again for the plugin and for considering this request! Looking forward to the next version :)

**Comment by tillkruss** [comment]
Sure. Let's add the actions and filter. Just one question, why do you want to `clone` the `$value` if it's an object and not just passing it?

**Comment by jeremyclarke** [comment]
Honestly I don't know what that's about. That was the `return` value previously, so we used it to populate $value before running the action+filter. Maybe it covers an edge-case that the original author thought was important?

**Comment by tillkruss** [comment]
I've added the hooks in 1b439e9b8c165577d3c085c93f968ca7caa57194, please test it. If it works well, I'll release the next version soon.
