### ISSUE TITLE
1.2.1 fatal error with HHVM 3.11.0

### ISSUE THREAD

**Issue by BernardZijlstra** [tillkruss/Redis-Object-Cache#20]
Hallo Till,

I get the following error with WordPress when using HipHop VM 3.11.0 (rel), all works fine with PHP 5.6. The object-cache.php file is equal to redis-cache/includes/object-cache.php. It does not matter if the plugin is active or not.

WordPress: 4.4
Redis-Cache: 1.2.1

Fatal error: Uncaught TypeError: Argument 2 passed to stream_set_blocking() must be an instance of int, bool given in /srv/www/40/wordpress/object-cache.php:377\nStack trace:\n#0 /srv/www/40/wordpress/object-cache.php(377): Redis->connect()\n#1 /srv/www/40/wordpress/object-cache.php(158): WP_Object_Cache->__construct()\n#2 /srv/www/40/wordpress/wp-includes/load.php(473): wp_cache_init()\n#3 /srv/www/40/wordpress/wp-settings.php(95): wp_start_object_cache()\n#4 /srv/www/40/wordpress/wp-config.php(124): include()\n#5 /srv/www/40/wordpress/wp-load.php(37): include()\n#6 /srv/www/quadzero/40/wp-blog-header.php(12): include()\n#7 /srv/www/quadzero/40/index.php(17): include()\n#8 {main}

Warning: strcasecmp() expects parameter 2 to be string, null given in /srv/www/40/wordpress/object-cache.php on line 358

**Comment by tillkruss** [comment]
It looks like HHVM's Redis extension is calling `stream_set_blocking()` with `true` instead of `1`: https://github.com/facebook/hhvm/blob/master/hphp/system/php/redis/Redis.php#L1653

I'd recommend that you open a issue in the HHVM project.

**Comment by BernardZijlstra** [comment]
Okay wil do thanks.

**Comment by BernardZijlstra** [comment]
Pull request has been filed and accepted https://github.com/facebook/hhvm/pull/6664
