### ISSUE TITLE
Repo link

### ISSUE THREAD

**Issue by szepeviktor** [tillkruss/Redis-Object-Cache#21]
Could you set https://wordpress.org/plugins/redis-cache/ as repo URL? On the top of this page
https://github.com/tillkruss/Redis-Object-Cache there's an `Edit` link for you.

**Comment by tillkruss** [comment]
Done.

**Comment by szepeviktor** [comment]
THanks.

Do you know https://github.com/pantheon-systems/wp-redis ?

**Comment by tillkruss** [comment]
Yes. I wanted to offer a plugin that supports Predis as well.

**Comment by szepeviktor** [comment]
OK.
