### ISSUE TITLE
Ability to disable caching from config file constant?

### ISSUE THREAD

**Issue by docmattman** [tillkruss/Redis-Object-Cache#25]
During development, I'd like to have caching turned off.  Is there a way I can set a config constant like `WP_DISABLE_REDIS_CACHE` that would turn off the object caching?  If this isn't available, I'll suggest doing something like the following (which could replace the current object-cache.php drop-in file and still make everything function the same when not disabled):

*wp-content/object-cache.php*

```
<?php
/*
Plugin Name: Redis Object Cache
Plugin URI: http://wordpress.org/plugins/redis-cache/
Description: A persistent object cache backend powered by Redis. Supports HHVM's Redis extension, the PCEL Redis Extension and the Predis library for PHP.
Version: 1.2.2
Author: Till Krüss
Author URI: http://till.kruss.me/
License: GPLv3
License URI: http://www.gnu.org/licenses/gpl-3.0.html

Based on Eric Mann's and Erick Hitter's Redis Object Cache:
https://github.com/ericmann/Redis-Object-Cache
*/

// Don't use cache if disabled from the config file, instead, use the WP default
if(WP_DISABLE_REDIS_CACHE === true) return require_once realpath(__DIR__.'/../wp-includes/cache.php');

// Use redis-cache plugin if not disabled.
return require_once(realpath(__DIR__.'/plugins/redis-cache/includes/object-cache.php'));
```

It basically just tells it to use the WP default if the WP_DISABLE_REDIS_CACHE  constant is set to true in the config, otherwise, it loads up the plugin normally.

**Comment by tillkruss** [comment]
You can just delete the `object-cache.php` in `/wp-content/` or disable the cache via the UI.

**Comment by docmattman** [comment]
Yes, but if I do that, its harder to re-enable later. The object-cache.php file will be deleted, and I'll have to manually copy it back for it to work again.  It would be nice to be able to disable and re-enable it without the extra step. The code I put above should accomplish that and avoid copying the code feom the includes/object-cache.php file.

**Comment by tillkruss** [comment]
What if you keep the `object-cache.php` in your code repository, so it will be deployed to your production environment, but you delete the file on your local development setup?

**Comment by docmattman** [comment]
I definitely could do that.  I was more looking for a way to turn it on/off easier.  A quick config variable change seems like the easiest to me.  Not a huge deal if it can't be done.  Just a nice-to-have convenience feature.

**Comment by tillkruss** [comment]
If more people request this feature, I'll implement it. For now your solution is much of a major change.

**Comment by jeremyclarke** [comment]
FWIW I would welcome this change too, especially since it's so small and unlikely to break anything. 

Using the UI works okay, but in a Git-controlled environment I'd rather not depend on WP moving files around if I can avoid it. 

Personally I use the redis object cache when developing locally because I want to test the caching throughout the process, and when I want to disable it I just use the command line to turn off Redis (which works too), so I wouldn't use this too often. At the same time I'd rather use a constant I comment on/off than the command line so this change would be nice. 

Thanks for considering it tilkruss, this plugin rocks.

**Comment by tillkruss** [comment]
Yeah, I totally get the use-case of this. I ran into this issue as well during development.

I'm not keen on requiring other files in `object-cache.php` (other than Predis). If you guys wanna check out all other object cache backends and see if anyone does it relatively smart, I'm happy to copy their approach.

**Comment by docmattman** [comment]
The code I presented above only includes the default `object-cache.php` file that comes built into Wordpress and you're own file (no other 3rd party code).  Basically, it just checks a `WP_DISABLE_REDIS_CACHE` config constant and if it's true, it will default back to "stock" Wordpress.  If it's false, it will load up your cache plugin just the same.  I've replaced my `object-cache.php` with the code above and everything seems to be working well.  I'm still testing it, but it does allow me to control the cache with the `WP_DISABLE_REDIS_CACHE` config constant and I haven't seen any issues so far.

I've only been testing it in a single development environment, so it's not very extensive.  Can you see any reason why the change would cause issues?

**Comment by tillkruss** [comment]
I understand the code.

I suggest you improve it and run it for a while and see how that goes. Make sure you cover if someone deactivates the plugin, or deletes the plugin folder.

**Comment by rajan281197** [comment]
How can I purge specific page Redis Cache?

if not possible then what is the way to Purge the Specific page Redis cache.

Lets me explain by the below example.

If I have Page **About Us** & **Contact Us** but I want if I purge the Cache of About Us Page it not Purge the Cache of Contact Us Page.

Basically, I want Page-Specific Purge Functionality so Please let me know how I implement this type of functionality.
