### ISSUE TITLE
Status: Not Connected after updated to 1.3

### ISSUE THREAD

**Issue by asasmoyo** [tillkruss/Redis-Object-Cache#28]
Status:	Not Connected
Client:	PECL Extension (v2.2.8-dev)

The redis configuration still use the old configs, but it says not connected. I use php 7.0.3 on centos.

**Comment by tillkruss** [comment]
Does it work when you use `v1.2.3`?

**Comment by asasmoyo** [comment]
I am not sure about the version number. But it should be the version before 1.3 update.

**Comment by tillkruss** [comment]
I really need to write tests.

Could you please try and replace line 339:

```
$server[ $setting ] = constant( $constant );
```

With this line:

```
$parameters[ $setting ] = constant( $constant );
```

And let me know if it works then?

**Comment by asasmoyo** [comment]
Oh nice! It says connected now :D.

**Comment by tillkruss** [comment]
Thanks a lot! I'll release a v1.3.1 in a few minutes.
