### ISSUE TITLE
Redis Not Installed

### ISSUE THREAD

**Issue by hordeim** [tillkruss/Redis-Object-Cache#3]
Posted the same on Wordpress - not sure which one you prefer

I use roots.io/bedrock and am trying to get object caching to work.  I have redis installed and the following works fine:

    <?php
       //Connecting to Redis server on localhost
       $redis = new Redis();
       $redis->connect('127.0.0.1', 6379);
       echo "Connection to server sucessfully";
       //check whether server is running or not
       echo "Server is running: "+ $redis->ping();
    ?>

I can see the ping through redis-cli monitor

Unfortunately, using your plugin, it shows that Redis is not installed (using the same 127.0.0.1/6379).

I also get the following:
Notice: Undefined property: WP_Object_Cache::$redis_client in /srv/http/site/web/wp/wp-includes/cache.php on line 327

**Comment by tillkruss** [comment]
The notice was fixed in 57f2d86.
