### ISSUE TITLE
Could you provide the way to get redis client object

### ISSUE THREAD

**Issue by pawawat** [tillkruss/Redis-Object-Cache#35]
Could you provide the way to get redis client object. for example make $redis attribute of WP_Object_Cache a public attr

**Comment by tillkruss** [comment]
Could you explain what you need it for?

**Comment by pawawat** [comment]
I want to utilize $redis object to do some task. if I can use your $redis object, I will have not to initiate a new connection

**Comment by tillkruss** [comment]
Added in https://github.com/tillkruss/Redis-Object-Cache/commit/52834c46e66777f67349f18834b11f64add86717.

**Comment by pawawat** [comment]
Thank you. BTW, When will you release a new version?

**Comment by tillkruss** [comment]
In a couple of days.
