### ISSUE TITLE
WP_CACHE_KEY_SALTis not unique if undefined in wp-config

### ISSUE THREAD

**Issue by zorrobyte** [tillkruss/Redis-Object-Cache#4]
In file:
redis-cache/includes/object-cache.php

		/**
		 * This approach is borrowed from Sivel and Boren. Use the salt for easy cache invalidation and for
		 * multi single WP installs on the same server.
		 */
		if ( ! defined( 'WP_CACHE_KEY_SALT' ) ) {
			define( 'WP_CACHE_KEY_SALT', '' );
		}

This doesn't work as it simply sets the WP_CACHE_KEY_SALT to null.

I have tested with multiple WP sites on the same host and the 2nd blog fails.

**Comment by zorrobyte** [comment]
Submitted pull request

**Comment by tillkruss** [comment]
What do you mean by "fails"?

**Comment by zorrobyte** [comment]
Whitescreens with no PHP error messages - due to two sites using same salt for different databases.

Do a redis-cli monitor and add two sites on the same server, there is no prefix and will cause DB corruption, errors.

**Comment by tillkruss** [comment]
Thanks for the explanation. That occurs only when two WordPress installations use the same `$table_prefix` on the same machine as mentioned [in the plugin notes](https://wordpress.org/plugins/redis-cache/other_notes/).

Manually defining a `WP_CACHE_KEY_SALT ` will solve this issue.

**Comment by zorrobyte** [comment]
Thank you for the update!

As I plan on using this on my Shared Hosting service, cPanel by default seems to use the same table prefix per account causing issues. It won't be a bother to maintain a forked private version.
