### ISSUE TITLE
Database 0 is used instead of  WP_REDIS_DATABASE

### ISSUE THREAD

**Issue by redhell** [tillkruss/Redis-Object-Cache#7]
Hey,

i used define(WP_REDIS_DATABASE, 4) to select database 4 but instead db0 is used.

redis-cli -> info prints out following

db0:keys=579,expires=19,avg_ttl=96766820
db4:keys=1,expires=19,avg_ttl=32306

The admin page shows me correctly that database 4 is used.

**Comment by hans2103** [comment]
cannot reproduce

in my wp-config.php I defined DB1 instead of DB0
> define('WP_REDIS_DATABASE', '1');

and while DB0 is still empty DB1 is increasing.

**Comment by redhell** [comment]
I noticed that there is no difference between single quotes or without.

db4 won't fill with keys but db0 increases.
Which version do you use? 
I use:
- redis 3.0.2.
- predis (latest git) with php 5.6.10
- latest wordpress
- latest plugin version in wordpress repo

**Comment by hans2103** [comment]
- redis 2.2.4
- PHPRedis 
- latest wordpress
- latest plugin version

**Comment by tillkruss** [comment]
Are you using Predis or the PCEL Redis Extension?

**Comment by redhell** [comment]
I'm using the PCEL extension but i tried preids but had no success.

**Comment by tillkruss** [comment]
Like @hans2103, I can't reproduce this. I'd recommend you ask your developer to have a closer look at this.

**Comment by redhell** [comment]
@tillkruss I found the mistake:

I added the define(..); under require_once(wp_settings.php) and it didn't work. After I added the defines at the top everything works well.

**Comment by tillkruss** [comment]
Awesome, glad it's working now.

**Comment by jonpasquier** [comment]
> @tillkruss I found the mistake:
> 
> I added the define(..); under require_once(wp_settings.php) and it didn't work. After I added the defines at the top everything works well.

Hi, 
I came here for the same problem, @redhell suggestions helped to fix it.
I guess I'm not the only one to have this problem, so I have proposed a change in the wiki page about configuration: https://github.com/rhubarbgroup/redis-cache/wiki

Thanks!

**Comment by tillkruss** [comment]
Thanks, we'll re-doing the docs #421.
