### ISSUE TITLE
Redis status : Unknown 

### ISSUE THREAD

**Issue by rjdp** [tillkruss/Redis-Object-Cache#8]
![selection_004](https://cloud.githubusercontent.com/assets/7734938/8829128/9ff48530-30b2-11e5-9e33-82ecc4a3f672.png)

**Comment by tillkruss** [comment]
Try deleting your `object-cache.php` and installing it again via the plugin ui.

**Comment by rjdp** [comment]
Thanks, My bad ... needeed to remove w3tc plugin and also deleted object-cache.php.

**Comment by tillkruss** [comment]
Great, I'm glad that solved it.
