### ISSUE TITLE
Not working with advanced-cache.php

### ISSUE THREAD

**Issue by rohmann** [tillkruss/Redis-Object-Cache#9]
I'm using this with batcache and getting this error:
`Fatal error: Call to undefined function maybe_unserialize()`

Adding this to object-cache.php did the trick:
```
if (!function_exists('maybe_unserialize')) {
	require_once(ABSPATH . 'wp-includes/functions.php' );
}
```

**Comment by rohmann** [comment]
Looked into this a bit more, and I don't think it's possible to use `maybe_serialize` and `maybe_unserialize` with `advanced-cache.php`. Those functions load after advanced-cache.php is loaded.

I patched my `object-cache.php` to use alternate functions for now.

**Comment by tillkruss** [comment]
Okay. If I get more users reporting the same issue, I'll remove the use of `maybe_(un)serialize()`.

**Comment by rohmann** [comment]
@tillkruss, would you consider accepting PR? My patch simply involves adding variants of those functions to the main class.

**Comment by tillkruss** [comment]
Thanks! Sure, submit it the PR. I probably won't merge it until more people report the same issue, tho.

**Comment by rohmann** [comment]
submitted

**Comment by tillkruss** [comment]
Merged.

**Comment by rohmann** [comment]
awesome thanks!
